
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Redshadow
 */
public class serverGUI extends javax.swing.JFrame {
    StyledDocument doc;
    Style style;
    Server server;
    /**
     * Creates new form serverGUI
     */
    public serverGUI(){
        super("Server");
        initComponents();
        doc = outputField.getStyledDocument();
        style = outputField.addStyle("output", null);
        StyleConstants.setForeground(style, Color.red);
        try {
            doc.insertString(doc.getLength(), "stopped", style);
        } catch (BadLocationException ex) {
            Logger.getLogger(serverGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        server = new Server(style, doc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        portLabel = new javax.swing.JLabel();
        startB = new javax.swing.JButton();
        stopB = new javax.swing.JButton();
        port = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputField = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        portLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        portLabel.setText("Port:");

        startB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        startB.setForeground(new java.awt.Color(51, 153, 0));
        startB.setText("START");
        startB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBActionPerformed(evt);
            }
        });

        stopB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stopB.setForeground(new java.awt.Color(153, 0, 0));
        stopB.setText("STOP");
        stopB.setEnabled(false);
        stopB.setMaximumSize(new java.awt.Dimension(87, 31));
        stopB.setMinimumSize(new java.awt.Dimension(87, 31));
        stopB.setPreferredSize(new java.awt.Dimension(87, 31));
        stopB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBActionPerformed(evt);
            }
        });

        port.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        port.setText("6175");
        port.setToolTipText("specify server port");
        port.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        outputField.setEditable(false);
        outputField.setBackground(new java.awt.Color(240, 240, 240));
        outputField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(outputField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(portLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startB, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stopB, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(portLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(startB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stopB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(port))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBActionPerformed
        if (Integer.parseInt(port.getText()) > 65536 || Integer.parseInt(port.getText()) < 0){
            JOptionPane.showMessageDialog(rootPane, "Invalid Port", "error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        startB.setEnabled(false);
        stopB.setEnabled(true);
        StyleConstants.setForeground(style, Color.green);
        try {
            doc.insertString(doc.getLength(), "\nrunning...", style);
        } catch (BadLocationException ex) {
            Logger.getLogger(serverGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        server.startServer(Integer.parseInt(port.getText()));
    }//GEN-LAST:event_startBActionPerformed

    private void stopBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBActionPerformed
        startB.setEnabled(true);
        stopB.setEnabled(false);
        StyleConstants.setForeground(style, Color.red);
        try {
            doc.insertString(doc.getLength(), "\nstopped", style);
        } catch (BadLocationException ex) {
            Logger.getLogger(serverGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        server.stopServer();
    }//GEN-LAST:event_stopBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(serverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(serverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(serverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(serverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new serverGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane outputField;
    private javax.swing.JFormattedTextField port;
    private javax.swing.JLabel portLabel;
    private javax.swing.JButton startB;
    private javax.swing.JButton stopB;
    // End of variables declaration//GEN-END:variables
}
